remove cache related and invalid args

diff --git a/.github/workflows/ci-tests.yml b/.github/workflows/ci-tests.yml
--- a/.github/workflows/ci-tests.yml
+++ b/.github/workflows/ci-tests.yml
@@ -108,9 +108,8 @@ jobs:
         run: echo 'PIP_EXTRA_INDEX_URL=--extra-index-url https://download.pytorch.org/whl/test/cpu/' >> $GITHUB_ENV
       - name: Install pkg
         run: |
-          uv pip --version
           uv pip install . -U "setuptools==69.5.1" -r requirements/_doctest.txt \
-            $PIP_EXTRA_INDEX_URL --find-links="$PYPI_CACHE_DIR"
+            $PIP_EXTRA_INDEX_URL
           uv pip list
         timeout-minutes: 25
 
@@ -131,9 +130,9 @@ jobs:
               python adjust-torch-versions.py $fpath
           done
           uv pip install --requirement requirements/clustering.txt -U \
-            $PIP_EXTRA_INDEX_URL --find-links="$PYPI_CACHE_DIR" || true # separate install to avoid conflicts and ignore failures
-          uv pip install --requirement requirements/_devel.txt -U --upgrade-strategy=eager \
-            $PIP_EXTRA_INDEX_URL --find-links="$PYPI_CACHE_DIR"
+            $PIP_EXTRA_INDEX_URL || true # separate install to avoid conflicts and ignore failures
+          uv pip install --requirement requirements/_devel.txt -U \
+            $PIP_EXTRA_INDEX_URL
           uv pip list
         timeout-minutes: 25
 
